# Generated by Django 6.0.6 on 2026-08-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_delivery_fee_remove_order_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cake_name',
            new_name='cakename',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='createdat',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_email',
            new_name='customeremail',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='customername',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_phone',
            new_name='customerphone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address',
            new_name='deliveryaddress',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date',
            new_name='deliverydate',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_time',
            new_name='deliverytime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='special_instructions',
            new_name='specialinstructions',
        ),
    ]
