# Generated by Django 6.0.6 on 2026-08-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flavour',
        ),
    ]
